# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TSWeChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire', '~> 4.0'
	pod 'Kingfisher'
	pod 'ObjectMapper', '~> 3.4'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'Dollar', '7.1.0'
	pod 'Cent', :git => 'https://github.com/ashitanojoe/Cent.git'
	pod 'KeychainAccess', '3.2.0'
	pod 'UIColor_Hex_Swift', '~> 5.1.0'
	pod 'RxCocoa', '~> 5'
	pod 'RxSwift'
	pod 'RxBlocking', '~> 5'
	pod 'XCGLogger', '~> 7.0.0'
	pod 'SnapKit', '~> 5.0.0'
	pod "BSImagePicker", "~> 2.10.0"
	pod 'ImagePicker'
	pod 'TSVoiceConverter', '0.1.6'
	pod 'XLActionController', '5.0.0'
	pod 'TimedSilver', '1.2.0'

	pod 'YYText', '1.0.7'
	pod 'SVProgressHUD', '2.0.4'
	pod 'INTULocationManager', '4.3.2'

	pod 'Reveal-SDK', '~> 4', :configurations => ['Debug']

end
